# Generated by Django 4.1.7 on 2023-03-23 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_mgmt_app', '0002_teacher_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_name', models.TextField(max_length=120)),
                ('std_address', models.TextField(max_length=250)),
                ('std_age', models.IntegerField()),
                ('join_date', models.DateField(auto_now_add=True)),
                ('std_image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_mgmt_app.course_model')),
            ],
        ),
    ]
